### PR TITLE
also succeeded to install on windows now

### PR DESCRIPTION
**Pull request by drandreaskrueger**

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks for the pull request! Could you integrate the latest changes on master that embed TestRPC instead of having it be a global dependency?

**Comment by drandreaskrueger** [comment]
Tried it:

```
npm uninstall -g node-gyp
npm uninstall -g ethereumjs-testrpc
npm uninstall -g web3
npm uninstall -g solidity-repl
```

then again:

```
npm install -g solidity-repl
```

and yes, it is working.

**Comment by drandreaskrueger** [comment]
Also, testrpc is now auto-started. Well done.

**Comment by raineorshine** [comment]
Thanks!

**Pull request merged**
